services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  ${POSTGRES_VOLUME}:
