services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  web:
    image: ${GHCR_NAMESPACE}
    ports:
      - 127.0.0.1:${REMOTE_DIST_PORT}:3000
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data_prod:
