services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_preprod:/var/lib/postgresql/data

  web:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NODE_ENV: preproduction
    depends_on:
      - db
    command: sh -c "npm run build && npm run start"

volumes:
  postgres_data_preprod:
