FROM node:20

WORKDIR /home/node/app

COPY package*.json ./

COPY . .

RUN npm install

RUN npm run build

ENV NODE_ENV=production

ENV PAYLOAD_CONFIG_PATH=dist/payload.config.js

WORKDIR /home/node/app

COPY package*.json  ./

RUN npm install --production

EXPOSE 3000

CMD ["npm", "run", "start"]